import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { analysisAPI } from '../utils/api';
import Results from './Results';
import { Scan, AlertTriangle, Loader2 } from 'lucide-react';

export default function SharedResult() {
    const { token } = useParams();
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchAnalysis = async () => {
            try {
                const result = await analysisAPI.getSharedAnalysis(token);
                setData(result);
            } catch (err) {
                console.error("Failed to load shared analysis:", err);
                setError("This share link is invalid or has expired.");
            } finally {
                setLoading(false);
            }
        };

        if (token) {
            fetchAnalysis();
        }
    }, [token]);

    if (loading) {
        return (
            <div className="min-h-screen bg-gray-950 flex flex-col items-center justify-center">
                <Loader2 className="w-12 h-12 text-indigo-500 animate-spin mb-4" />
                <p className="text-gray-400">Verifying security token...</p>
            </div>
        );
    }

    if (error) {
        return (
            <div className="min-h-screen bg-gray-950 flex flex-col items-center justify-center p-6 text-center">
                <div className="w-20 h-20 bg-rose-500/10 rounded-full flex items-center justify-center mb-6">
                    <AlertTriangle className="w-10 h-10 text-rose-500" />
                </div>
                <h1 className="text-2xl font-bold text-white mb-2">Access Denied</h1>
                <p className="text-gray-400 max-w-md mb-8">{error}</p>
                <Link
                    to="/"
                    className="px-6 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition-colors"
                >
                    Go to VeriFace Home
                </Link>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-950 relative overflow-hidden font-sans pb-20">
            {/* Background */}
            <div className="fixed inset-0 gradient-mesh opacity-30 pointer-events-none" />

            {/* Navbar (Simplified for Public View) */}
            <nav className="relative z-50 border-b border-white/5 bg-black/20 backdrop-blur-md">
                <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-indigo-600 rounded-lg">
                            <Scan className="w-5 h-5 text-white" />
                        </div>
                        <span className="text-xl font-bold tracking-tight text-gradient">
                            VeriFace
                        </span>
                    </div>

                    <Link
                        to="/"
                        className="text-sm text-gray-400 hover:text-white transition-colors"
                    >
                        Run your own analysis &rarr;
                    </Link>
                </div>
            </nav>

            {/* Main Content */}
            <main className="relative z-10 max-w-7xl mx-auto px-6 pt-12">
                <div className="text-center mb-10">
                    <span className="inline-block px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-semibold uppercase tracking-wider mb-4">
                        Shared Analysis Result
                    </span>
                    <h1 className="text-3xl md:text-4xl font-bold text-white mb-2">
                        Forensic Authenticity Report
                    </h1>
                    <p className="text-gray-400">
                        Generated by VeriFace AI
                    </p>
                </div>

                <Results data={data} isPublicView={true} />
            </main>
        </div>
    );
}
